name: "postprocess"
backend: "python"

input [
  {
    name: "post_input1"
    data_type: TYPE_FP32
    dims: [ -1, 6 ]
  },
  {
    name: "post_input2"
    data_type: TYPE_INT32
    dims: [ -1 ]
  }
]

output [
  {
    name: "post_output"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

instance_group [
  {
      count: 1
      kind: KIND_CPU
  }
]