backend: "fastdeploy"

# Input configuration of the model
input [
  {
    # input name
    name: "image"
    # input type such as TYPE_FP32、TYPE_UINT8、TYPE_INT8、TYPE_INT16、TYPE_INT32、TYPE_INT64、TYPE_FP16、TYPE_STRING
    data_type: TYPE_FP32
    # input shape， The batch dimension is omitted and the actual shape is [batch, c, h, w]
    dims: [ -1, 3, -1, -1 ]
  },
  {
    name: "scale_factor"
    data_type: TYPE_FP32
    dims: [ -1, 2 ]
  },
  {
    name: "im_shape"
    data_type: TYPE_FP32
    dims: [ -1, 2 ]
  }
]

# The output of the model is configured in the same format as the input
output [
  {
    name: "matrix_nms_0.tmp_0"
    data_type: TYPE_FP32
    dims: [ -1, 6 ]
  },
  {
    name: "matrix_nms_0.tmp_2"
    data_type: TYPE_INT32
    dims: [ -1 ]
  }
]

# Number of instances of the model
instance_group [
  {
    # The number of instances is 1
    count: 1
    # Use GPU, CPU inference option is:KIND_CPU
    kind: KIND_GPU
    # The instance is deployed on the 0th GPU card
    gpus: [0]
  }
]

optimization {
  execution_accelerators {
  gpu_execution_accelerator : [ {
    # use Paddle engine
    name: "paddle",
  }
  ]
}}
